import 'package:flutter/material.dart';

import './models/category.dart';
import './models/meal.dart';

const DUMMY_CATEGORIES = [
  Category(
    id: 'c1',
    title: 'Plato Fuerte',
    color: Color(0xff00c853),
  ),
  Category(
    id: 'c2',
    title: 'Espagueti',
    color: Color(0xff00c853),
  ),
  Category(
    id: 'c3',
    title: 'Chimi',
    color: Color(0xff00c853),
  ),
  Category(
    id: 'c4',
    title: 'Desayuno',
    color: Color(0xff00c853),
  ),
  Category(
    id: 'c5',
    title: 'Postres',
    color: Color(0xff00c853),
  ),
  Category(
    id: 'c6',
    title: 'Bebidas',
    color: Color(0xff00c853),
  ),
  Category(
    id: 'c7',
    title: 'Todos',
    color: Color(0xff00c853),
  ),
];

const DUMMY_MEALS = [
  Meal(
    id: 'm1',
    categories: ['c4', 'c7'],
    title: 'Mangu con los tres golpes',
    complexity: Complexity.Simple,
    imageUrl:
        'https://aseasonedgreeting.com/wp-content/uploads/2020/03/Mangu-with-pickled-red-onions.jpg',
    duration: 20,
    ingredients: [
      '4 plátanos verdes',
      '1½ cucharadita sal',
      '4 cucharadas mantequilla o aceite de oliva',
      'taza agua, a temperatura ambiente',
      '1 cebolla roja, grande',
      '2 cucharadas aceite de oliva',
      '1 cucharadita vinagre de frutas',
      '½ cucharadita sal, (o más, al gusto)',
      '12 huevos, medianos',
      '1 taza aceite de freír, (se usará para freír el salami y el queso también)',
    ],
    steps: [
      'Pela y hierve los plátanos en una olla grande. Machácalos con un tenedor o un pasapurés en un bol grande.',
      'Sofríe las cebollas a fuego lento y añade sal y pimienta en vinagre.',
      'Calentar el aceite a fuego medio en una sartén antiadherente. Fríe los huevos como te gusten.',
      'Fríe el queso hasta que esté dorado y crujiente.',
      'Fríe el salami en el aceite calentado a fuego medio-alto, dándole la vuelta para que se dore por ambos lados. Retíralo del aceite y déjalo reposar sobre una toalla de papel para que absorba el exceso de aceite.',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm2',
    categories: ['c1', 'c7'],
    title: 'Sancocho',
    complexity: Complexity.Simple,
    imageUrl:
        'https://salimaskitchen.com/wp-content/uploads/2023/09/Stewed-Sancocho-Puerto-Rican-Beef-Root-Veggie-Stew-Salimas-Kitchen-26.jpg',
    duration: 81,
    ingredients: [
      '1/2 cucharadita de hojas de orégano seco',
      '1/2 cucharadita de hojas de tomillo seco',
      '1/2 cucharadita de cilantro seco molido',
      '2 cucharadas de aceite vegetal',
      '2 pounds carne de res o de cabra, cortados en cubos',
      '1 pound pechuga de pollo sin hueso y sin pellejo, cortadas en cubitos',
      '1 cebolla grande, picada',
      '1 pimiento verde (pimentón), picado',
      '3 dientes de ajo, picados',
      '5 tazas de agua',
      '1 camote (ayuma) grande, pelado y cortado en cubitos',
      '1 papa mediana, pelada y cortada en cubitos',
      '1 plátano verde, en trozos de 3 cm',
      '1 pound jamón, cortado en trozos pequeños',
      '2 cucharaditas de salsa picante (Opcional)'
    ],
    steps: [
      'Combina el orégano, el tomillo y el cilantro en un recipiente pequeño. Sazona la carne de res con la mitad de esta combinación de hierbas. Calienta el aceite en una olla grande a fuego medio-alto y cocina la carne hasta que pierda el color rosado. Saca la carne de la olla y resérvalo. Sazona el pollo con las hierbas restantes y cocínalo en la misma olla hasta que pierda el color rosado. Saca el pollo de la olla y resérvalo. Cocina la cebolla, el pimiento verde y el ajo hasta que estén tiernos. Añade mas aceite si es necesario.',
      'Añade la carne a los vegetales en la olla. Agrega el agua, el camote, la papa, el plátano verde, y el caldo. Deja hervir y reduce el fuego a medio-bajo. Tapa la olla y cocina durante 30 minutos. Añade el pollo y el jamón. Tapa la olla. Cocina durante 40 minutos adicionales hasta que la carne esté tierna. Machaca los plátanos, el camote y las papas en la misma olla. Agrega el maíz, las alcaparras y la salsa picante. Cocina durante 10 minutos o hasta que el maíz esté tierno.'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm3',
    categories: ['c1', 'c7'],
    title: 'Mofongo',
    complexity: Complexity.Simple,
    imageUrl:
        'https://salimaskitchen.com/wp-content/uploads/2022/12/Traditional-Puerto-Rican-Mofongo-Salimas-Kitchen-29.jpg',
    duration: 15,
    ingredients: [
      '2 tazas de agua caliente',
      '2 tazas de aceite vegetal para freír',
      '6 plátanos verdes pelados y cortados en rodajas de una pulgada',
      '4 dientes de ajo, finamente picados',
      '1 cucharada de aceite de oliva',
      '1/2 libra de tocineta o 6 tiras de tocino frito, picado'
    ],
    steps: [
      'Calienta el aceite vegetal en una sartén grande y fríe los plátanos durante 15 minutos sin o hasta que estén tiernos (no dejes que se doren). Escúrrelos sobre toallas de papel.',
      'Machaca los plátanos en un mortero o pilón grande. Agrega el ajo, el aceite de oliva y la tocineta y continúa machacándolos hasta que estén bien mezclados. Agrega el caldo disuelto y mezcla bien hasta que esté suave.',
      'Consejos: Forma el Mofongo en bolas y sírvelo con carne de puerco, pollo, pavo o res. El mofongo también se puede usar como relleno de pavo.'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm4',
    categories: ['c1', 'c7'],
    title: 'Locrio de Pollo',
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.thepetitgourmet.com/wp-content/uploads/2015/06/DSCN8417.jpg',
    duration: 50,
    ingredients: [
      '2 libras de pollo sin pellejo',
      '2 cucharadas de aceite vegetal',
      '1 cebolla mediana, picada',
      '1 pimiento verde, en cubitos',
      '2 dientes de ajo, picados',
      '2 tazas de agua',
      '1 lata (15 onzas) de salsa de tomate',
      '1/2 cucharadita de orégano seco',
      '1/2 cucharadita de tomillo seco',
      '2 1/2 tazas de arroz de grano largo',
      '2 cucharadas de cilantro fresco picado'
    ],
    steps: [
      'Desmenuza 1 tableta del caldo y espolvoréala sobre los dos lados del pollo.',
      'Calienta el aceite en una olla grande a fuego medio-alto y cocina el pollo por todos los lados hasta que quede dorado.',
      'Retira de la olla y reserva. Agrega la cebolla, el pimiento y el ajo. Cocínalos mezclando frecuentemente hasta que la cebolla esté tierna.',
      'Agrega el pollo, el agua, la salsa de tomate, el caldo restante, el orégano y el tomillo.',
      'Mézclalo bien y agrega el arroz. Deja que hierva y reduce el fuego a bajo. Tápala y cocínalo durante 30 minutos o hasta que el líquido se evapore y el arroz quede tierno. Sírvelo inmediatamente con cilantro picado.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm5',
    categories: ['c1', 'c7'],
    title: 'La Bandera Dominicana',
    complexity: Complexity.Simple,
    imageUrl:
        'https://tuguiadominicana.com/wp-content/uploads/2023/03/el-conuco-@elconucord.jpg',
    duration: 80,
    ingredients: [
      '5 cucharadas aceite vegetal, (soya, maní o maíz)',
      '4 tazas arroz',
      '4 cucharaditas sal',
      '2 tazas habichuelas rojas, pintas o giras secas',
      '¼ cucharadita orégano',
      '1 ají cubanela, o pimiento morrón picado',
      '1 cebolla roja, pequeña cortada en cuartos',
      '2 dientes ajo, majados',
      '1 taza auyama, cortada en cubos',
      '½ taza salsa de tomate',
      '½ cucharadita cilantro',
      '▢1 cucharadita sal',
      '2 libras pollo',
      '1 cucharadita azúcar',
      '2 tazas agua',
      '¼ cucharaditas pimienta',
      '2 tomates',
      '½ lechuga',
      '1 pepino, cortado en rebanadas o cubos',
      '3 cucharadas vinagre de frutas'
    ],
    steps: [
      'En un caldero de aluminio mediano  (mínimo 2.5 litros [0.5 gal] de capacidad) calienta 3 cucharadas de aceite a fuego medio al que has agregado la sal. Cuando el aceite esté un poco caliente agrega 6 tazas [1.4 litros] de agua, cuidándote de las salpicaduras.',
      'Cuando el agua alcance el punto de ebullición agrega el arroz, y cuece, revolviendo regularmente para evitar que se adhiera excesivamente al fondo.',
      'Cuando el agua se haya evaporado cubre con la tapa y cuece a fuego muy bajo (pero que genere vapor) por 15 minutos.',
      'En un caldero calienta el aceite a temperatura media. Agrega orégano, ají, cebolla, ajo, auyama, salsa de tomate, apio, tomillo y cilantro. Cuece removiendo por medio minuto.',
      'Vierte 4 tazas del agua en la que hirvieron las habichuelas (completa con agua fresca si es necesario). Una vez que llegue a ebullición, machaca ligeramente las habichuelas con un pasapurés para desprenderlas de la piel y hacer habichuelas más cremosas.',
      'Corta el pollo en trozos pequeños y colócalo en un bol que tenga una tapa. Condimenta los trozos de pollo con el jugo de limón.',
      'Mezcla el pollo, orégano, cebolla, apio, sal y ajo. Deja reposar tapado en la nevera durante 30 minutos.',
      'Calienta el aceite a fuego medio en un caldero mediano, añade el azúcar y espera a que se torne de un color dorado oscuro. Añade el pollo (reserva todas las demás cosas del marinado para usarlas más adelante) y cocina removiendo hasta que la carne esté ligeramente dorada.',
      'Añade 2 cucharadas de agua. Tapa y cocina a fuego medio durante 15 minutos, removiendo y añadiendo agua por cucharadas a medida que sea necesario para evitar que se queme.',
      'Añade los vegetales que habías reservado de marinar el pollo, más cubanela, tomates y aceitunas. Tapa, y cocina a fuego lento hasta que los vegetales estén bien cocidos, agregando agua por cucharadas y revolviendo cuando sea necesario.',
      'Añade la salsa de tomate y media taza de agua, hierve a fuego bajo para producir una salsa ligera. Los vegetales estarán muy blandos, la salsa un poco espesa, y el pollo se desprende de los huesos fácilmente.'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm6',
    categories: ['c2', 'c7'],
    title: 'Espaguetis rojos',
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.recetasnestle.com.do/sites/default/files/srh_recipes/465ffb6f3bb041a97de9834892f58c1e.jpg',
    duration: 25,
    ingredients: [
      '1 lb de spaguetis',
      '1 cucharada aceitunas y alcaparras',
      '2 cucharada aceite de oliva',
      '1 ají verde grande cortado en cubitos',
      '4 tomates maduros cornados en cubitos',
      '4 cucharadas pasta de tomate',
      '1 cebolla picada',
      '1/4 cucharadita pimienta negra molida',
      '1 cucharadita orégano',
      '2 cucharadas cilantro picado',
      '2 dientes ajo machacado',
      '1/3 taza agua',
      '1/4 taza parmesano rallado',
      'Sal'
    ],
    steps: [
      'Hervir la pasta en abundante agua y sal hasta que esté al dente. Cortar todos los vegetales. Calienta el aceite. Sofríe la cebolla, ajo, ajíes, aceitunas alcaparras hasta que los vegetales estén blandos. Añade los tomates y vinagre y revuelve. Agrega la pasta de tomate y mezcla bien',
      'Agrega el agua y revuelve. Agrega los espaguetis y mezcla. Pon el cilantro, pimienta, orégano y sal al gusto. Espolvorea el queso y sirvase caliente.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm7',
    categories: ['c3', 'c7'],
    title: 'Chimi',
    complexity: Complexity.Simple,
    imageUrl:
        'https://micocinadominicana.com/wp-content/uploads/2019/07/Dominican-Chimi-Burger-Smart-Little-Cookie-3-600x900.jpg',
    duration: 30,
    ingredients: [
      '½ taza mayonesa',
      '¼ taza jugo de naranja',
      '½ taza Ketchup',
      '1 cebolla, pequeña cortada en cubitos pequeños',
      '1 ají cubanela, cortado en cubitos pequeños',
      '2 libras carne de res molida',
      '2 tazas repollo, picado finamente',
      '6 panes de agua , o panes para hamburguesas',
    ],
    steps: [
      'Mezcla la mayonesa, jugo de naranja y ketchup.',
      'Mezcla cebolla en cubitos, ají, ajo y orégano con la carne, agrega salsa inglesa, y sal y mezcla bien. Divide la carne en 6 porciones y forma las tortitas (alargadas para pan de agua, redondas para pan de hamburguesas)',
      'Calienta la plancha a fuego alto. Unta de aceite la plancha y cuece la carne, rotándola regularmente hasta que esté bien cocida.',
      'Aplica un poco más de aceite a la plancha y calienta el pan sobre esta.',
      'Pon la carne, cebolla, tomate y repollo entre los panes. Agrega salsa extra a tu gusto.',
      'Sírvelo enseguida.'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm8',
    categories: ['c5', 'c7'],
    title: 'Arroz con dulce',
    complexity: Complexity.Simple,
    imageUrl:
        'https://bakeitwithlove.com/wp-content/uploads/2022/04/Arroz-con-Dulce-Puerto-Rican-rice-pudding-sq.jpg',
    duration: 90,
    ingredients: [
      '6 tazas de agua tibia, uso dividido',
      '1 taza de arroz blanco de grano largo',
      '2 palitos de canela (de 4 pulgadas), 8 extra para adornar',
      '12 clavos',
      '2 anís estrellas',
      '1 cucharadita de sal',
      '1 lata de leche carnation',
      '1 taza de azúcar granulada',
      '1/4 taza de pasas',
      '2 cucharadas de mantequilla',
      'Nuez moscada molida para decorar'
    ],
    steps: [
      'Combina 2 tazas de agua, arroz, 2 palitos de canela, clavo de olor y anís estrella en una cacerola grande. Deja remojar durante mínimo 1 hora.',
      'Coloca la cacerola a fuego medio; añade las 4 tazas de agua restantes y la sal. Hierve durante 2 minutos. Desecha los palitos de canela, clavos y anís estrella.',
      'Reduce el fuego a bajo; agrega la leche evaporada, el azúcar y las pasas. Cose durante 10 minutos o hasta que la mezcla espese. Retira del fuego.',
      'Agrega la mantequilla y revuelve; cubre y deja enfriar.',
      'Sirve adornado con nuez moscada y 8 palitos de canela restantes',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm9',
    categories: ['c5', 'c7'],
    title: 'Habichuelas con dulce',
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.recetasnestle.com.do/sites/default/files/srh_recipes/5d9783df08c33cc04fa16a284d3e87fb.png',
    duration: 250,
    ingredients: [
      '1 libra de habichuelas (frijoles) rojas oscuras secas, escogidas y enjuagadas',
      'Agua, uso dividido',
      '2 palitos de canela, uso dividido',
      '8 clavos de olor, uso dividido',
      '1 a 2 batatas o boniatos medianos (de 3/4 a 1 1/2 libras), pelados, cortados en pedazos de 1 pulgada',
      '2 latas de leche carnation',
      '1 taza de leche de coco',
      '3/4 taza de azúcar granulada',
      '1/2 cucharadita de sal',
      '1/2 cucharadita de nuez moscada en polvo',
      '1/2 taza de uvas pasas',
      'Galletas de leche para la decoración (opcional)',
    ],
    steps: [
      'Pon de 6 a 8 tazas de agua en un tazón grande y remoja las habichuelas toda la noche; escúrrelas. Coloca las habichuelas en una cacerola grande; agrega esa misma cantidad de agua. Cocínalas con un hervor suave a fuego medio-bajo, con la tapa de medio lado y revolviéndolas de vez en cuando de 1 a 1 1/2 hora o hasta que estén tiernas. Escúrrelas; ponlas a un lado.',
      'Haz que hiervan 4 tazas de agua, 1 palito de canela y 2 clavos de olor en una cacerola grande. Agrega la batata. Reduce el fuego a medio; cocínala de 12 a 15 minutos o hasta que esté tierna. Escúrrela; reserva el agua que utilizaste (la necesitarás en el próximo paso). Retira los condimentos.',
      'Coloca aproximadamente 1/3 de las habichuelas en el procesador de alimentos o en la licuadora; agrega 1/2 taza del agua en que cocinaste la batata. Pon la tapa; procesa esto hasta obtener una pasta espesa. (La mezcla debe tener la consistencia de la crema agria.) Vierte el puré de las habichuelas en un tazón grande pasándolo por un colador de malla fina a fin te quitarle los pedazos de piel. Repite este procedimiento con el resto de las habichuelas y del agua de la batata que reservaste.',
      'Haz que hiervan la leche evaporada, la leche de coco, el azúcar, la sal, el resto de la canela y los 6 clavos restantes a fuego medio en una cacerola grande. Reduce el fuego a bajo; cocina esto, revolviendo constantemente, durante 15 minutos. Retira los clavos.',
      'Agrega las habichuelas, las uvas pasas y la nuez moscada a la mezcla de leche (la mezcla tendrá la consistencia del aceite). Cocina esto 10 minutos revolviéndolo con frecuencia. Agrega la batata ya cocida; sigue cocinando todo de 10 a 15 minutos mientras lo revuelves con frecuencia hasta obtener la consistencia de la crema espesa. Saca el palito de canela.',
      'Sirve el postre caliente o frío en tazas soperas o de poste. Decóralo con las galletas de leche.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm10',
    categories: ['c6', 'c7'],
    title: 'Morir Soñando',
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.imperialsugar.com/sites/default/files/recipe/Morir-Sonando-imperial.jpg',
    duration: 10,
    ingredients: [
      '4 tazas leche evaporada',
      '1 cucharada extracto de vainilla',
      '¾ taza azúcar, (podrías no usarla toda)',
      '2 tazas hielo, en cubos (puede ser partido)',
      '2 ½ tazas jugo de naranja'
    ],
    steps: [
      'Pon la leche en el congelador hasta que la leche esté bien fría.',
      'Mezcla la leche con azúcar al gusto y remueve, agrega vainilla. Agrega hielo y remueve. Vierte lentamente el jugo de naranja en la leche y revuelve vigorosamente.',
      'Vierte en 6 vasos largos, y sirve de immediato.',
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
];
